# -*- coding: utf-8 -*-
"""Aula3sub

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GKnTrqWIZDporRpqeCBlWcCoNPi1kcKc
"""

# ETE PORTO DIGITAL
# DISCIPLINA: PLPC1
# PROFESSOR: CLOVIS
# ESTUDANTE: SILVIO RICARDO

print ("Olá, ETE PORTO DIGITAL!")